"""
Clinical history and AI evaluation Request and Response schemas for Clerkship API.
"""

from typing import Any, Dict, Optional
from pydantic import Field
from app.schemas.base import BaseSchema
from app.schemas.consultas import ConsultationResponse


class AiEvaluationSummary(BaseSchema):
    """Formative rubric and evaluation generated by AI."""

    final_score: float
    feedback_summary: Optional[str] = None
    execution_time_seconds: Optional[float] = None
    detailed_rubric: Dict[str, Any] = Field(default_factory=dict)


class FeedbackResponse(BaseSchema):
    """Consultation and its corresponding AI formative feedback."""

    consultation: ConsultationResponse
    evaluation: AiEvaluationSummary


class StudentStatisticsResponse(BaseSchema):
    """Aggregate metrics of student simulations and clinical reasoning performance."""

    total_simulaciones: int = 0
    completadas: int = 0
    en_progreso: int = 0
    promedio_score: Optional[float] = 0.0
    puntaje_maximo: Optional[float] = 0.0
    puntaje_minimo: Optional[float] = 0.0
    por_especialidad: Dict[str, int] = Field(default_factory=dict)

